# Generated by Django 3.2.4 on 2021-06-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blue', '0002_framework_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('movies', models.ManyToManyField(to='blue.Movie')),
            ],
        ),
    ]
